import Head from 'next/head'
import { ActionCard } from '../components/home/ActionCard'

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid place-items-center h-4/5">
        <ActionCard />
      </div>
    </>
  )
}
